name: AdamTeece
favicon: null
layout_spectrum: 0.63142
typography_spectrum: 0.22279
title: Just my thoughts and ramblings while I learn to use The Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-316315-10
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.36436049873009324
  lightness: 0.47366305673494935
  saturation: 0.753136393148452
  rhythmicContrast: 0.4545414496678859
purpose: []
